### ISSUE TITLE
question of data put

### ISSUE THREAD

**Issue by xiaohaijie** [FilAlves/micro-primers#7]
“Section 1: Pre-processing: the user must indicate the sequence of the adapters used afer the restriction 
enzyme action and the pattern remaining in the sequence afer the digestion. If the data was not produced by 
restriction enzyme this option can be disabled at this section as well.”

Hello, I would like to ask if the data you want to enter is a comparison sequence of multiple individuals of a species with a reference base set instead of enzymatic digestion, then can micro-primers be used? I saw the above paragraph in the literature, does it mean that the example I said can be used? How do I disable this parameter? Are there operating instructions?Thank you！

**Comment by FilAlves** [comment]
Hi @xiaohaijie, 

Yes, you can use micro-primers for your purpose. You can deactivate the "Restriction enzime pattern" filter in `settings > Pre-Prossessing` in the GUI, or by ommiting the `-enz` flag on the terminal.
